export const capabilities = [
    {
        id: "frontend",
        icon: "code",
        label: "Frontend",
        title: "React / HTML / CSS / JavaScript",
        detail: "Dựng giao diện responsive, rõ trạng thái, có motion vừa đủ và dễ bảo trì sau khi bàn giao.",
        level: "Core",
        cluster: "ui",
        depth: "core",
        status: "active",
        relatedProjects: ["tca-crypto-analyzer", "bonario-product-hub"],
        relatedWorkflowSteps: ["02", "03", "04"],
    },
    {
        id: "product-ui",
        icon: "dashboard",
        label: "Product UI",
        title: "Dashboards & Admin tools",
        detail: "Thiết kế màn hình dữ liệu, bộ lọc, bảng điều khiển và thao tác lặp lại cho đội vận hành.",
        level: "Strong",
        cluster: "data",
        depth: "strong",
        status: "active",
        relatedProjects: ["tca-crypto-analyzer", "bonario-product-hub"],
        relatedWorkflowSteps: ["01", "02", "03"],
    },
    {
        id: "backend-flow",
        icon: "api",
        label: "Backend flow",
        title: "API / Flask / Odoo Integration",
        detail: "Kết nối endpoint, chuẩn hóa dữ liệu và xây flow xử lý giữa frontend với service nội bộ.",
        level: "Applied",
        cluster: "systems",
        depth: "applied",
        status: "active",
        relatedProjects: ["bonario-product-hub"],
        relatedWorkflowSteps: ["01", "03", "04"],
    },
    {
        id: "automation",
        icon: "automation",
        label: "Automation",
        title: "AI-assisted development",
        detail: "Kết hợp AI assistant, log, script và browser audit để debug, kiểm thử UI và triển khai nhanh hơn.",
        level: "Active",
        cluster: "delivery",
        depth: "active",
        status: "active",
        relatedProjects: ["ai-operator-workflow"],
        relatedWorkflowSteps: ["01", "03", "04"],
    },
];
