export const projects = [
    {
        slug: "tca-crypto-analyzer",
        title: "TCA Crypto Analyzer",
        type: "Market data dashboard",
        category: "dashboard",
        importance: "flagship",
        year: "2026",
        image: "/assets/signal-case-tca-dashboard.webp",
        tech: ["Next.js", "Charts", "Binance API"],
        summary:
            "Dashboard theo dõi crypto market, gom biểu đồ, tín hiệu và dữ liệu biến động vào một trải nghiệm đọc nhanh.",
        problem:
            "Trader phải mở nhiều nguồn để xem chart, biến động và tín hiệu, khiến việc đọc thị trường bị chậm và dễ nhiễu.",
        role: "Thiết kế cấu trúc dashboard, tổ chức module dữ liệu, định nghĩa trạng thái hiển thị và luồng đọc tín hiệu.",
        outcome:
            "Tạo một màn hình tập trung giúp ưu tiên tín hiệu quan trọng, giảm thao tác chuyển tab và hỗ trợ ra quyết định nhanh hơn.",
        status: "Private build",
        timeline: "Prototype + dashboard iteration",
        privateReason: "Private because market data and account context are not public.",
        team: "Solo frontend/product UI",
        evidenceNote: "Sanitized interface preview is used; live market/account data stays private.",
        nextProof: "Add a redacted demo clip or public sandbox when data can be safely mocked.",
        liveUrl: "",
        repoUrl: "",
        constraints: [
            "Nhiều nguồn dữ liệu",
            "Ưu tiên tốc độ đọc",
            "Giảm chuyển tab",
        ],
        deliverables: [
            "Dashboard information architecture",
            "Signal-first card and chart hierarchy",
            "Runtime states for loading, empty and fast-scan flows",
        ],
        uiFocus: [
            "dashboard hierarchy",
            "signal prioritization",
            "fast scanning",
        ],
        systemRole: "Signal-first market reading surface",
        signals: ["clarity", "speed", "data-density"],
        assets: {
            cover: "/assets/signal-case-tca-dashboard.webp",
        },
        links: {},
    },
    {
        slug: "bonario-product-hub",
        title: "Bonario Product Hub",
        type: "Internal operations tool",
        category: "internal-tool",
        importance: "high",
        year: "2026",
        image: "/assets/signal-case-bonario-hub.webp",
        tech: ["Flask", "React", "Odoo"],
        summary:
            "Công cụ web kết nối Flask, React và Odoo để tra cứu, xử lý và kiểm soát dữ liệu sản phẩm nội bộ.",
        problem:
            "Đội vận hành cần xử lý dữ liệu sản phẩm nhanh hơn nhưng thao tác đang phân tán giữa nhiều màn hình và nguồn dữ liệu.",
        role: "Kết nối API, dựng giao diện quản trị, tổ chức dữ liệu theo workflow và tối ưu các thao tác lặp lại.",
        outcome:
            "Tạo một hub rõ trạng thái, dễ mở rộng, giúp thao tác sản phẩm nhất quán hơn và giảm phụ thuộc vào xử lý thủ công.",
        status: "Internal tool",
        timeline: "Internal workflow build",
        privateReason: "Private because it touches operations data and Odoo context.",
        team: "Solo full-stack implementation support",
        evidenceNote: "Sanitized preview only; internal product/Odoo data cannot be published.",
        nextProof: "Add redacted workflow screenshots for search, edit, sync, and error states.",
        liveUrl: "",
        repoUrl: "",
        constraints: [
            "Nhiều nguồn dữ liệu",
            "Nhu cầu thao tác lặp",
            "Odoo integration",
        ],
        deliverables: [
            "Operations hub structure",
            "Admin workflow screens",
            "API/Odoo state handling and operator feedback",
        ],
        uiFocus: ["state clarity", "admin flows", "operational consistency"],
        systemRole: "Operations hub for product handling",
        signals: ["workflow", "system-state", "reliability"],
        assets: {
            cover: "/assets/signal-case-bonario-hub.webp",
        },
        links: {},
    },
    {
        slug: "ai-operator-workflow",
        title: "AI Operator Workflow",
        type: "Development workflow",
        category: "workflow",
        importance: "high",
        year: "2026",
        image: "/assets/signal-case-ai-workflow.webp",
        tech: ["Codex", "Claude", "MCP"],
        summary:
            "Bộ workflow dùng AI assistant, Windows, WSL2, MCP và browser audit để đọc code, sửa lỗi và kiểm tra sản phẩm nhanh hơn.",
        problem:
            "Khi làm nhiều dự án song song, context, checklist kiểm thử và cách debug dễ bị phân tán qua nhiều công cụ.",
        role: "Thiết kế quy trình làm việc với AI, CLI, script kiểm tra, browser runtime và ghi chú kỹ thuật có thể tái sử dụng.",
        outcome:
            "Rút ngắn vòng lặp debug, chuẩn hóa cách review UI/UX và giữ được context kỹ thuật qua nhiều phiên làm việc.",
        status: "Living system",
        timeline: "Active personal workflow",
        privateReason: "Publicly explainable, but exact session logs and client context stay private.",
        team: "Personal workflow system",
        evidenceNote: "Process can be described publicly; raw session logs and client context stay private.",
        nextProof: "Publish a cleaned walkthrough of plan, diff, build, browser QA, and check-in handoff.",
        liveUrl: "",
        repoUrl: "",
        constraints: [
            "Nhiều tool song song",
            "Context switching",
            "Debug loops",
        ],
        deliverables: [
            "Reusable AI/CLI operating loop",
            "Browser QA and layout-check scripts",
            "Session memory and handoff documentation",
        ],
        uiFocus: [
            "workflow clarity",
            "automation hooks",
            "runtime verification",
        ],
        systemRole: "Operator workflow system",
        signals: ["automation", "verification", "speed"],
        assets: {
            cover: "/assets/signal-case-ai-workflow.webp",
        },
        links: {},
    },
];
