export const sceneConfig = [
    {
        id: "home",
        chapter: "00",
        scene: "boot",
        label: "home",
        railLabel: {
            story: "entry",
            systems: "overview",
            cases: "intro",
            recruiter: "summary",
        },
        shellHint: {
            story: "story entry point",
            systems: "systems overview",
            cases: "portfolio intro",
            recruiter: "frontend summary",
        },
        modeVisibility: ["story", "systems", "cases", "recruiter"],
        modeOrder: { story: 0, systems: 0, cases: 0, recruiter: 0 },
        modePresentation: {
            story: "full",
            systems: "full",
            cases: "full",
            recruiter: "full",
        },
        modeTone: {
            story: "secondary",
            systems: "support",
            cases: "support",
            recruiter: "secondary",
        },
    },
    {
        id: "identity",
        chapter: "01",
        scene: "identity",
        label: "identity",
        navLabel: {
            story: "mindset",
            systems: "approach",
            cases: "context",
            recruiter: "fit",
        },
        railLabel: {
            story: "mindset",
            systems: "approach",
            cases: "context",
            recruiter: "fit",
        },
        shellHint: {
            story: "mindset and operating principles",
            systems: "system reading approach",
            cases: "builder context behind the cases",
            recruiter: "role fit snapshot",
        },
        modeVisibility: ["story", "systems", "cases", "recruiter"],
        modeOrder: { story: 1, systems: 5, cases: 4, recruiter: 5 },
        modePresentation: {
            story: "full",
            systems: "compact",
            cases: "compact",
            recruiter: "compact",
        },
        modeTone: {
            story: "primary",
            systems: "support",
            cases: "support",
            recruiter: "secondary",
        },
    },
    {
        id: "stack",
        chapter: "02",
        scene: "stack",
        label: "stack",
        navLabel: {
            story: "stack",
            systems: "systems",
            cases: "capability",
            recruiter: "stack",
        },
        railLabel: {
            story: "stack",
            systems: "systems",
            cases: "capability",
            recruiter: "stack",
        },
        shellHint: {
            story: "supporting capability layer",
            systems: "capability matrix",
            cases: "capabilities behind the cases",
            recruiter: "core tools and delivery surface",
        },
        modeVisibility: ["story", "systems", "cases", "recruiter"],
        modeOrder: { story: 3, systems: 1, cases: 3, recruiter: 3 },
        modePresentation: {
            story: "compact",
            systems: "full",
            cases: "compact",
            recruiter: "compact",
        },
        modeTone: {
            story: "secondary",
            systems: "primary",
            cases: "support",
            recruiter: "secondary",
        },
    },
    {
        id: "projects",
        chapter: "03",
        scene: "projects",
        label: "projects",
        navLabel: {
            story: "cases",
            systems: "surfaces",
            cases: "theater",
            recruiter: "highlights",
        },
        railLabel: {
            story: "cases",
            systems: "surfaces",
            cases: "theater",
            recruiter: "highlights",
        },
        shellHint: {
            story: "selected narrative cases",
            systems: "system surfaces and outputs",
            cases: "case theater and evidence",
            recruiter: "featured work highlights",
        },
        modeVisibility: ["story", "systems", "cases", "recruiter"],
        modeOrder: { story: 2, systems: 3, cases: 1, recruiter: 1 },
        modePresentation: {
            story: "full",
            systems: "full",
            cases: "full",
            recruiter: "full",
        },
        modeTone: {
            story: "primary",
            systems: "secondary",
            cases: "primary",
            recruiter: "primary",
        },
    },
    {
        id: "workflow",
        chapter: "04",
        scene: "workflow",
        label: "workflow",
        navLabel: {
            story: "flow",
            systems: "pipeline",
            cases: "loop",
            recruiter: "process",
        },
        railLabel: {
            story: "flow",
            systems: "pipeline",
            cases: "loop",
            recruiter: "process",
        },
        shellHint: {
            story: "delivery rhythm behind the story",
            systems: "workflow pipeline",
            cases: "delivery loop behind the cases",
            recruiter: "execution process and validation",
        },
        modeVisibility: ["story", "systems", "cases", "recruiter"],
        modeOrder: { story: 4, systems: 2, cases: 2, recruiter: 4 },
        modePresentation: {
            story: "compact",
            systems: "full",
            cases: "compact",
            recruiter: "compact",
        },
        modeTone: {
            story: "support",
            systems: "primary",
            cases: "secondary",
            recruiter: "secondary",
        },
    },
    {
        id: "contact",
        chapter: "05",
        scene: "contact",
        label: "contact",
        navLabel: {
            story: "brief",
            systems: "intake",
            cases: "next case",
            recruiter: "hire",
        },
        railLabel: {
            story: "brief",
            systems: "intake",
            cases: "next case",
            recruiter: "hire",
        },
        shellHint: {
            story: "project brief handoff",
            systems: "intake for context and constraints",
            cases: "turn a brief into the next case",
            recruiter: "hiring or collaboration entry",
        },
        modeVisibility: ["story", "systems", "cases", "recruiter"],
        modeOrder: { story: 5, systems: 4, cases: 5, recruiter: 2 },
        modePresentation: {
            story: "full",
            systems: "compact",
            cases: "full",
            recruiter: "full",
        },
        modeTone: {
            story: "primary",
            systems: "secondary",
            cases: "secondary",
            recruiter: "primary",
        },
    },
];

export const sceneLookup = Object.fromEntries(
    sceneConfig.map((record) => [record.id, record]),
);
